name: giwon-blog

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giwon-blog
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - blog-network
    environment:
      - NODE_ENV=production

networks:
  blog-network:
    external: true
